---
title: "FOI_time varying"
author: "Phuong Huynh Thi"
date: "02/05/2019"
output: html_document
---


```{r set wd, echo=FALSE, message=FALSE}
# Changeable: site:KH or HC?, step year 1, 2 or 5
site <- "KH"
dataInput <-"C3D1" # 6 cases: C1D1, C2D1, C3D1, C1F1, C2F1, C3F1
step_year <- 4 # 1 to 5

setwd("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/FOI/Time varying")

##Results from different IS and infecting serotype infering models:
if ( dataInput == "C1D1"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_C1D1.csv")  
}
if ( dataInput == "C2D1"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_C2D1.csv")  
}
if ( dataInput == "C3D1"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_C3D1.csv")  
}
if ( dataInput == "C1F1"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_HomoAssigned_C1F1.csv")  
}
if ( dataInput == "C2F1"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_HomoAssigned_C2F1.csv")  
}
if ( dataInput == "C3F1"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_HomoAssigned_C3F1.csv")  
}


data$YEAR <- as.factor(data$YEAR)
data$predictedIS<- ordered(data$predictedIS,levels=c("Secondary","Primary","Neg"))
data$pred.serotype<- as.factor(data$pred.serotype)

## result from lowest AIC model and homotypic responses were assigned the serotype in advance of applying infecting model
## 
# data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2_to_7_June2018/pop data/models/models_modified_titers/Infecting serotype Models/PredictedIS_batch567_pred.serotype_HomoAssigned.csv")

pop<- data[which(!is.na(data$AGE_MIN)&is.na(data$PanbioUnit)),]#cross out acute and ELISA samples
pop$Site <- substr(pop$sampleID,1,2)

#Agegroup_ 1year
pop$AgeGroup <- factor(as.factor(floor(pop$Age)),labels=c("[1-2)","[2-3)","[3-4)","[4-5)","[5-6)","[6-7)","[7-8)","[8-9)","[9-10)","[10-11)","[11-12)","[12-13)","[13-14)","[14-15)","[15-16)","[16-17)","[17-18)","[18-19)","[19-20)","[20-21)","[21-22)","[22-23)","[23-24)","[24-25)","[25-26)","[26-27)","[27-28)","[28-29)","[29-30)","[30,31)"))# group as  1year 1 group.

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
## Agegroup_ 2 years : 16groups

# pop$AgeGroup <-factor(as.factor(floor(pop$Age/2)+1),labels=c("[1-2)","[2-4)","[4-6)","[6-8)","[8-10)","[10-12)","[12-14)","[14-16)","[16-18)","[18-20)","[20-22)","[22-24)","[24-26)","[26-28)","[28-30)","[30-31)"))

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
##Agegroup_3years : 11 groups

# pop$AgeGroup <- floor(pop$Age/3) + 1
# pop$AgeGroup[which(pop$AgeGroup == 11)] <- 10
# pop$AgeGroup <- factor(
#   pop$AgeGroup,
#   labels = c("[1-3)","[3-6)","[6-9)","[9-12)","[12-15)","[15-18)",
#              "[18-21)","[21-24)","[24-27)","[27-31)"))
#              
```


```{r data input, echo=FALSE, message=FALSE}

library(dplyr)
library(tidyr)
# spread(x,y): spread rows of col x into collums, then value of col y will fit in as rows.
#rename(new_name=old_name).

if (site=="HC"){
   p_year=dplyr::filter(pop,Site=="HC")%>%group_by(AgeGroup,YEAR,Site)%>%dplyr::count(predictedIS)%>%spread(predictedIS,n)}
if(site == "KH"){
    p_year=dplyr::filter(pop,Site=="KH")%>%group_by(AgeGroup,YEAR,Site)%>%dplyr::count(predictedIS)%>%spread(predictedIS,n)}

# p_year$total <- apply(p_year[,3:8],1,sum,na.rm=T)

p_year$total <- apply(p_year[,4:6],1,sum,na.rm=T)
p_year <- p_year[order(p_year$YEAR),]

#create function for substr age rather than put age in order, this is useful in case of missing data in a specific age: 
my_substr <- function(s){
  if (nchar(s) == 5){
    t <- substr(s, 4, 4)
  }else{
    if (nchar(s) == 6){
      t <- substr(s, 4, 5)
    }else{
      t <- substr(s, 5, 6)
    }
  }
  return(t)
}

#
p_year$age<- apply(p_year[,1],1,my_substr)

# Assign NA as 0 because stan does not support NA value:

for (idx in 4:6){
  idx.na <- which(is.na(p_year[[idx]]))
  p_year[[idx]][idx.na] <- 0
}



# setnames(p_year, old=c("AgeGroup","1","2","3","4","Neg","Secondary","total"),new=c("AgeGroup","DV1.13","DV2.13","DV3.13","DV4.13","Neg.13","Sec.13","total.13"))


```

This gets the data in the right format for stan.

```{r data format for stan, echo=FALSE,message=FALSE}

b = length(p_year$age)
n_y = 2017-2013+1+max(as.integer(p_year[which(p_year$YEAR==2013),]$age)) # number of years backward, time period that data is available ## KH: 36 -> 1982, HC: 35 -> 1983

if ( step_year == 2){
    if ( site == "KH"){
        vecj = as.integer(c(rep(1:floor(n_y/2), each =  2))) # for KH
    } else{
        vecj = as.integer(c(rep(1:floor(n_y/2), each =  2),17)) # for HC 
    }
} else if (step_year == 3){
    if ( site == "KH"){
        vecj = as.integer(c(rep(1:floor(n_y/3), each =  3))) #for KH
    } else{
        vecj = as.integer(c(rep(1:floor(n_y/3), each =  3),11,11)) # for HC
    }
}else if (step_year == 4){
    if ( site == "KH"){
        vecj = as.integer(c(rep(1:floor(n_y/4), each =  4))) #for KH
    } else{
        vecj = as.integer(c(rep(1:floor(n_y/4), each =  4),9,9,9)) # for HC 
    }
}else if (step_year == 5){
    if ( site == "KH"){
        vecj = as.integer(c(rep(1:floor(n_y/5), each =  5),7)) #for KH
    } else{
        vecj = as.integer(c(rep(1:floor(n_y/5), each =  5))) # for HC 
    }
}else { # step_year = 1
    vecj = as.integer(1:n_y)
}


lamb_y = length(unique(vecj)) # number of lambda over time


b = length(p_year$age)
datapp<- list(a = b,
              datap=c(p_year[1:b,6],
                      p_year[1:b,5],
                      p_year[1:b,4]),
              vecj = vecj,
              lamb_y = lamb_y,
              vecy = as.integer(as.character(p_year$YEAR)),
              veca = as.integer(p_year$age),
              n_y = n_y) # numbers of neg, prim,and sec respectively. 

# numbers of neg,prim1,prim2,prim3,prim4,and sec respectively. 

library(rstan)
# stan code has sections in it: functions, data (where you tell it what form the data will be in), 
#parameters where you say what parameters you are estimating,
#Transformed parameters where you transform these parameters to use in the model
#and the model where you specify how the data and model outcomes are linked

```


#Data description


```{r pop data description, }
# extract KH data 2016, 2017




```

