---
title: "Combined_FOI_Calculation"
author: "Phuong Huynh Thi, collated by Maxine Tan"
date: "9/4/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r set working directory}

rm(list=ls())

library(rstan)
util <- new.env()
source('stan_utility.R', local=util)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())


```

# indicate model type here!
## input site, data input, no. of steps for years
```{r data input & model selection, echo=FALSE, message=FALSE}
# Changeable 
site <- "HC" #KH, HC,HC&KH, KH&HC
dataInput <-"C1F3" # C1D1, C1D2, C1D3, C1F1, C1F2, C1F3
modelType <- "SS" # cons, SS, TVSS, TV
step_year <- 5 # non-TV models, input 0
#for time-varying model, options are 1,2,3,4,5

# # for loop to run at once
# site_vec <- c("KH","HC","KH&HC")
# dataInput_vec <- c("C1D1","C1F1")
# step_year_vec <- c(1:5)
# 
# for (idx_site_vec in 1:length(site_vec)){
#     for (idx_dataInput_vec in 1: length(dataInput_vec)){
#         for (idx_step_year_vec in 1: length(step_year_vec)){
# 
#             site <- site_vec[idx_site_vec]
#             dataInput <- dataInput_vec[idx_dataInput_vec]
#             step_year <- step_year_vec[idx_step_year_vec]
#             code function ........
#         }
#     }
# }


##Results from different IS and infecting serotype infering models:
if ( dataInput == "C1D1"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_C1D1.csv")  
}
if ( dataInput == "C1D3"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_C1D3.csv")  
}
if ( dataInput == "C2D3"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_C2D3.csv")  
}
if ( dataInput == "C3D3"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_C3D3.csv")  
}
if ( dataInput == "C1F1"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_HomoAssigned_C1F1.csv")  
}
if ( dataInput == "C1F3"){
    data <- read.csv("~/Dropbox/1.SHARED_FOLDER/slides_June_2018/PMA_batch2To7_July2019/pop data/models/Infecting serotype Model/PredictedIS_B23_567_pred.serotype_HomoAssigned_C1F3.csv")  
}

data$YEAR <- as.factor(data$YEAR)
data$predictedIS<- ordered(data$predictedIS,levels=c("Secondary","Primary","Neg"))
data$pred.serotype<- as.factor(data$pred.serotype)

# Extract population data only!
pop<- data[which(!is.na(data$AGE_MIN)&is.na(data$PanbioUnit)),]#cross out acute and ELISA samples
pop$Site <- substr(pop$sampleID,1,2)

# Age grouping

##Agegroup_ 1year
pop$AgeGroup <-factor(as.factor(floor(pop$Age)),labels=c("[1-2)","[2-3)","[3-4)","[4-5)","[5-6)","[6-7)","[7-8)","[8-9)","[9-10)","[10-11)","[11-12)","[12-13)","[13-14)","[14-15)","[15-16)","[16-17)","[17-18)","[18-19)","[19-20)","[20-21)","[21-22)","[22-23)","[23-24)","[24-25)","[25-26)","[26-27)","[27-28)","[28-29)","[29-30)","[30,31)"))# group as  1year 1 group.

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
## Agegroup_ 2 years : 16groups

# pop$AgeGroup <-factor(as.factor(floor(pop$Age/2)+1),labels=c("[1-2)","[2-4)","[4-6)","[6-8)","[8-10)","[10-12)","[12-14)","[14-16)","[16-18)","[18-20)","[20-22)","[22-24)","[24-26)","[26-28)","[28-30)","[30-31)"))

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
##Agegroup_3years : 11 groups

# pop$AgeGroup <- floor(pop$Age/3) + 1
# pop$AgeGroup[which(pop$AgeGroup == 11)] <- 10
# pop$AgeGroup <- factor(
#   pop$AgeGroup,
#   labels = c("[1-3)","[3-6)","[6-9)","[9-12)","[12-15)","[15-18)",
#              "[18-21)","[21-24)","[24-27)","[27-31)"))
#              
             
```

# data filtering and preparation
```{r data preparation, echo=FALSE, message=FALSE}

library(dplyr)
library(tidyr)
# spread(x,y): spread rows of col x into collums, then value of col y will fit in as rows.
#rename(new_name=old_name).

if (site=="HC"){
    p_year=dplyr::filter(pop,Site=="HC")%>%group_by(AgeGroup,YEAR,Site)%>%dplyr::count(pred.serotype)%>%spread(pred.serotype,n)}
if(site == "KH"){
    p_year=dplyr::filter(pop,Site=="KH")%>%group_by(AgeGroup,YEAR,Site)%>%dplyr::count(pred.serotype)%>%spread(pred.serotype,n)}
if(site == "KH&HC"|site =="HC&KH"){
    p_year=dplyr::filter(pop)%>%group_by(AgeGroup,YEAR,Site)%>%dplyr::count(pred.serotype)%>%spread(pred.serotype,n)}


# p_year$total <- apply(p_year[,3:8],1,sum,na.rm=T)
p_year$Primary <-rowSums(p_year[,4:7],na.rm = T)
p_year$total <-rowSums(p_year[,4:9],na.rm = T)

#create function for substr age rather than put age in order, this is useful in case of missing data in a specific age: 
my_substr <- function(s){
  if (nchar(s) == 5){
    t <- substr(s, 4, 4)
  }else{
    if (nchar(s) == 6){
      t <- substr(s, 4, 5)
    }else{
      t <- substr(s, 5, 6)
    }
  }
  return(t)
}

#
p_year$age<- apply(p_year[,1],1,my_substr)

# Assign NA as 0 because stan does not support NA value:

for (idx in 4:9){
  idx.na <- which(is.na(p_year[[idx]]))
  p_year[[idx]][idx.na] <- 0
}

# setnames(p_year, old=c("AgeGroup","1","2","3","4","Neg","Secondary","total"),new=c("AgeGroup","DV1.13","DV2.13","DV3.13","DV4.13","Neg.13","Sec.13","total.13"))


```

# data formatting for stan
```{r data format for stan, echo=FALSE,message=FALSE}

b = length(p_year$age)
n_y = 2017-2013+1+max(as.integer(p_year[which(p_year$YEAR==2013),]$age)) # number of years backward, time period that data is available ## KH: 36 -> 1982, HC: 35 -> 1983

# data input for constant FOI model
if (modelType == "cons") {
  datapp<- list(a = b,
              datap=c(p_year[1:b, 8],
                      p_year[1:b, 4],
                      p_year[1:b, 5],
                      p_year[1:b, 6],
                      p_year[1:b, 7],
                      p_year[1:b, 9]),
                      veca = as.integer(p_year$age))
}

# data input for serotype-specific FOI model
if (modelType == "SS") {
  datapp<- list(a = b,
              datap=c(p_year[1:b, 8],
                      p_year[1:b, 4],
                      p_year[1:b, 5],
                      p_year[1:b, 6],
                      p_year[1:b, 7],
                      p_year[1:b, 9]),
                      veca=as.integer(p_year$age))
}

#
if (modelType == "TV"|modelType == "TVSS"){
  
l_vecj = length(c(rep(1:ceiling(n_y/step_year), each =  step_year))) # ceiling: round up

datapp<- list(a = b,
              step_year = step_year,
              datap=c(p_year[1:b, 8],
                      p_year[1:b, 4],
                      p_year[1:b, 5],
                      p_year[1:b, 6],
                      p_year[1:b, 7],
                      p_year[1:b, 9]),
              vecj=as.integer(c(rep(1:ceiling(n_y/step_year), each =  step_year))),#for index of actual lambda
              l_vecj = length(c(rep(1:ceiling(n_y/step_year), each =  step_year))),# length of vecj for later use
              vecy=as.integer(as.character(p_year$YEAR)),
              veca=as.integer(p_year$age)) # numbers of neg, prim,and sec respectively.

}

```

# Stan codes 
```{r}
if (modelType == "cons"){
  FOI_Dengue <-"~/Dropbox/PMA_Github/PMA_dengue_v2/PMA codes/FoI/Stan/FOI_constant_MLE.stan"
}
if (modelType == "SS"){
  FOI_Dengue <-"~/Dropbox/PMA_Github/PMA_dengue_v2/PMA codes/FoI/Stan/FOI_serotype_specific_MLE.stan"
}
if (modelType == "TV"){
  FOI_Dengue <- "~/Dropbox/PMA_Github/PMA_dengue_v2/PMA codes/FoI/Stan/FOI_time varying_MLE.stan"
}
if (modelType == "TVSS"){
  FOI_Dengue <-"~/Dropbox/PMA_Github/PMA_dengue_v2/PMA codes/FoI/Stan/FOI_time varying_serotype specific_MLE.stan"
}

```

# run model and obtain posterior values
```{r result from model, echo=FALSE, message=FALSE,warning=FALSE, include=FALSE}
# you then run using this: From this output we can quickly assess model convergence by looking at the Rhat values for each parameter. When these are at or near 1, the chains have converged. There are many other diagnostics, but this is an important one for Stan.
set.seed(9)
 fit<-stan(file = FOI_Dengue,
          data=datapp, iter=6000,
          chains=4,
          cores = parallel::detectCores()) # this may be conducted via 2 steps:  stand_model() and sampling().
 
util$check_all_diagnostics(fit)
posterior <- rstan::extract(fit) # specify package rstan rather than tidyr
# str(posterior)
#this summarizes the parameters, gets mean,etc. of parameters and metrics of whether converged or not like Rhat and neff
foisummary <- summary(fit)
foisummary

tab <- data.frame(foisummary$summary)
if (modelType == "cons") {
  saveRDS(fit,paste("/home/phuong/pCloudDrive/PMA analysis results/FoI/RDS/FOI constant",p_year$Site[1],dataInput,".rds"))
} else if (modelType == "SS") {
  saveRDS(fit, paste("/home/phuong/pCloudDrive/PMA analysis results/FoI/RDS/FOI serotypes",p_year$Site[1],dataInput, ".rds"))
} else if (modelType == "TV") {
  saveRDS(fit, paste("/home/phuong/pCloudDrive/PMA analysis results/FoI/RDS/FOI timvarying",step_year,"yr(s)",p_year$Site[1],dataInput, ".rds"))
}else {
  saveRDS(fit,paste("/home/phuong/pCloudDrive/PMA analysis results/FoI/RDS/FOI timevarying_serotypes",step_year,"yr(s)",site,dataInput,".rds"))  
}

# # plot to see whether estimated parameter is convergence or not: traceplot
# plottedRows <- 1 : nrow(posterior$lambda)
# plottedRows <- which(plottedRows %% 6 == 0)
# plot(posterior$lambda[plottedRows, 4],type="l")

```

# plots for posterior values
```{r posterior distribution of lambda, echo=FALSE,fig.height=8,fig.width=12}
## constant FOI
if (modelType == "cons") {
  p <- data.frame(lambda = posterior$lambda)
p$year <- rep("FOI")
# violin plot
lamb <- ggplot(p, aes(x=year,y=lambda)) + geom_violin()+
  ggtitle(paste("posterior lambda _ constant",p_year$Site[1],dataInput))+
  coord_cartesian(ylim=c (0.0,0.03))+
  theme(plot.title = element_text(hjust=0.5,face="bold",size=20,colour = "blue"),
        axis.title.x = element_blank(),
        axis.text = element_text(face = "bold", angle = 0, hjust = 1))+
  # stat_summary(fun.y=mean, geom="point", size=2, color="red")+ # add mean
  # geom_boxplot(width=0.1)+# add median and quartile
  stat_summary(fun.data=mean_sdl, 
               geom="pointrange", color="red")#Add mean and standard deviation
# # save the figure
ggsave(filename=paste("/home/phuong/pCloudDrive/PMA analysis results/FoI/Lambda/FoI constant",site,dataInput,".png"),plot=lamb)
lamb
}

## serotype-specific FOI
if (modelType == "SS") {

  p <- data.frame(lambda = as.numeric(),
                DENV = as.character())

for(a in 1:4){
  p_temp <- data.frame(lambda = posterior$lambda[ , a],
                       DENV = paste0('DENV ', a))
  p <- rbind(p, p_temp)
}

# violin plot
lamb = ggplot(p, aes(x=DENV,y=lambda)) + geom_violin()+
  ggtitle(paste("FoI_serotype specific",site,dataInput))+
  theme(plot.title = element_text(hjust=0.5,face="bold",size=20,colour = "blue"),
        axis.title.x = element_blank(),
        axis.text = element_text(face = "bold"))+
    ylim(0,0.05)+
  # stat_summary(fun.y=mean, geom="point", size=2, color="red")+ # add mean
  # geom_boxplot(width=0.1)+# add median and quartile
  stat_summary(fun.data=mean_sdl, 
                 geom="pointrange", color="red")#Add mean and standard deviation

ggsave(filename = paste("/home/phuong/pCloudDrive/PMA analysis results/FoI/Lambda/FoI_ serotype specific",site,dataInput,".png" ),plot=lamb)
lamb

}

## time-varyingFOI
if (modelType == "TV") {
  #create dataframe for violin plot:
p <- data.frame(lambda = as.numeric(),
                YEAR = as.character()) 


for(a in 1:(l_vecj/step_year)){
  p_temp <- if(step_year ==1){
    data.frame(
      lambda = posterior$lambda[ ,a],
      YEAR = paste0(2018-(step_year*(a-1)+1)))# 1 year
  }else{
    data.frame(
      lambda = posterior$lambda[ ,a],
      YEAR = paste0(2018-(step_year*(a-1)+1),"-",2018-(step_year*(a-1)+1)-(step_year-1)))# period
    
  }
  
  p <- rbind(p, p_temp)
}

# violin plot
lamb <- ggplot(p, aes(x=YEAR,y=lambda)) + geom_violin()+
  ggtitle(paste("posterior lambda",step_year,"yr(s)",p_year$Site[1],dataInput))+
  ylim(-.01,0.2)+
  theme(plot.title = element_text(hjust=0.5,face="bold",size=20,colour = "blue"),
        axis.title.x = element_blank(),
        axis.text = element_text(face = "bold", angle = 90, hjust = 1))+
  # stat_summary(fun.y=mean, geom="point", size=2, color="red")+ # add mean
  # geom_boxplot(width=0.1)+# add median and quartile
  stat_summary(fun.data=mean_sdl, 
               geom="pointrange", color="red")#Add mean and standard deviation
ggsave(filename=paste("/home/phuong/pCloudDrive/PMA analysis results/FoI/Lambda/FOI_time varying",step_year,"yr(s)",p_year$Site[1],dataInput,".png"), plot = lamb)

lamb
}


## time-varying serotype-specific FOI
if (modelType == "TVSS"){
  #create dataframe for violin plot:
    
p <- data.frame(lambda = as.numeric(),
                DENV = as.character())

for(a in 1:4){
  p_temp <- data.frame(lambda = posterior$lambda[,a,],
                       DENV = paste0('DENV ', a))
  p <- rbind(p, p_temp)
}


## Grouping less info. yrs >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# #1. renames colnames of dataframe p as year, group less info. yrs
# if ( site == "HC"){
#     if ( step_year == 1)
#     {names(p) <- c(2017:1988,"87-83","DENV")}
#     if ( step_year ==2){
#         names(p) <- c("2017-2016","2015-2014","2013-2012","2011-2010","2009-2008","2007-2006","2005-2004","2003-2002","2001-2000","1999-1998","1997-1996","1995-1994","1993-1992","1991-1990","1989-1988","1987-1986","1985-1983","DENV")}
#     if (step_year ==5){
#         names(p) <- c("2017-2013","2012-2008","2007-2003","2002-1998","1997-1993","1992-1988","1987-1983","DENV")
#     }
# }else if ( site == "KH"){
# 
#     if ( step_year == 1)
#     {names(p) <- c(2017:1988,"87-82","DENV")}
#     if ( step_year ==2){
#         names(p) <- c("2017-2016","2015-2014","2013-2012","2011-2010","2009-2008","2007-2006","2005-2004","2003-2002","2001-2000","1999-1998","1997-1996","1995-1994","1993-1992","1991-1990","1989-1988","1987-1986","1985-1982","DENV")}
#     if (step_year ==5){
#         names(p) <- c("2017-2013","2012-2008","2007-2003","2002-1998","1997-1993","1992-1988","1987-1982","DENV")
# 
#     }}
# 

# Not grouping the very last years
#1.renames colnames of dataframe p as year, not grouping less info.yrs
if ( site == "HC"){
    if ( step_year == 1)# 35 lambda
    {names(p) <- c(2017:1983,"DENV")}
    if ( step_year ==2){# 18 lambda
        names(p) <- c("2017-2016","2015-2014","2013-2012","2011-2010","2009-2008","2007-2006","2005-2004","2003-2002","2001-2000","1999-1998","1997-1996","1995-1994","1993-1992","1991-1990","1989-1988","1987-1986","1985-1984","1983","DENV")}
    if ( step_year ==3){# 12 lambda
        names(p) <- c("2017-2015","2014-2012","2011-2009","2008-2006","2005-2003","2002-2000","1999-1997","1996-1994","1993-1991","1990-1988","1987-1985","1984-1983","DENV")}
    if ( step_year ==4){# 9 lambda
        names(p) <- c("2017-2014","2013-2010","2009-2006","2005-2002","2001-1998","1997-1994","1993-1990","1989-1986","1985-1983","DENV")}
    if (step_year ==5){ #7 lambda
        names(p) <- c("2017-2013","2012-2008","2007-2003","2002-1998","1997-1993","1992-1988","1987-1983","DENV")
    }
}else if ( site == "KH"|site =="KH&HC"|site =="HC&KH"){

    if ( step_year == 1) # 36 lambda
    {names(p) <- c(2017:1982,"DENV")}# 36 lambda 
    if ( step_year ==2){# 18 lambda
        names(p) <- c("2017-2016","2015-2014","2013-2012","2011-2010","2009-2008","2007-2006","2005-2004","2003-2002","2001-2000","1999-1998","1997-1996","1995-1994","1993-1992","1991-1990","1989-1988","1987-1986","1985-1984","1983-1982","DENV")}
     if ( step_year ==3){# 12 lambda
        names(p) <- c("2017-2015","2014-2012","2011-2009","2008-2006","2005-2003","2002-2000","1999-1997","1996-1994","1993-1991","1990-1988","1987-1985","1984-1982","DENV")}
    if ( step_year ==4){# 9 lambda
        names(p) <- c("2017-2014","2013-2010","2009-2006","2005-2002","2001-1998","1997-1994","1993-1990","1989-1986","1985-1982","DENV")}
    if (step_year ==5){ # 7 lambda + 1 lambda with one year data
        names(p) <- c("2017-2013","2012-2008","2007-2003","2002-1998","1997-1993","1992-1988","1987-1983","1982","DENV")

    }}


#2. violin plot, not grouping less info. yrs

    DV1 <- p[1:12000,-((l_vecj/step_year)+1)]
    DV2 <- p[(12001:24000),-((l_vecj/step_year)+1)]
    DV3 <- p[24001:36000,-((l_vecj/step_year)+1)]
    DV4 <- p[36001:48000,-((l_vecj/step_year)+1)]


# tranform data frame for ploting

library(reshape2)
DV1 <- melt(DV1,id.vars=0) # transformed data frame
DV2 <- melt(DV2,id.vars=0)
DV3 <- melt(DV3,id.vars=0)
DV4 <- melt(DV4,id.vars=0)

# DV1
p1 <- ggplot(DV1,aes(x=variable,y=value)) +
      geom_violin()+
      # geom_boxplot(width=0.1)+
        # ggtitle(paste("posterior lambda _ age varying_serotype specific",p_year$Site[1]))+
        theme(plot.title = element_text(hjust=0.5,face="bold",size=20,colour = "blue"),
              axis.title.x = element_blank(),
              # axis.text.x = element_text(angle = 90, hjust = 0.5,
              axis.text.x = element_blank())+
        coord_cartesian(ylim=c(-0.01,0.3))+
        ylab("DENV1")+
        # stat_summary(fun.y=mean, geom="point", size=2, color="red")+ # add mean
        # geom_boxplot(width=0.1)+# add median and quartile
        stat_summary(fun.data=mean_sdl, 
                     geom="pointrange", color="red")#Add mean and standard deviation
#DV2   
p2 <- ggplot(DV2,aes(x=variable,y=value)) + 
      geom_violin()+
      # geom_boxplot(width=0.1)+
        # ggtitle(paste("posterior lambda _ age varying_serotype specific",p_year$Site[1]))+
        theme(plot.title = element_text(hjust=0.5,face="bold",size=20,colour = "blue"),
              axis.title.x = element_blank(),
              # axis.text.x = element_text(angle = 90, hjust = 0.5,
              axis.text.x = element_blank())+
        coord_cartesian(ylim=c(-0.01,0.3))+
        ylab("DENV2")+
        # stat_summary(fun.y=mean, geom="point", size=2, color="red")+ # add mean
        # geom_boxplot(width=0.1)+# add median and quartile
        stat_summary(fun.data=mean_sdl, 
                     geom="pointrange", color="red")#Add mean and standard deviation
    
#DV3
p3 <- ggplot(DV3,aes(x=variable,y=value)) + 
      geom_violin()+
      # geom_boxplot(width=0.1)+
        # ggtitle(paste("posterior lambda _ age varying_serotype specific",p_year$Site[1]))+
        theme(plot.title = element_text(hjust=0.5,face="bold",size=20,colour = "blue"),
              axis.title.x = element_blank(),
              axis.text.x = element_text(angle = 90,size=6,face = "bold"))+
              # axis.text.x = element_blank())+
        coord_cartesian(ylim=c(-0.01,0.3))+
        ylab("DENV3")+
        # stat_summary(fun.y=mean, geom="point", size=2, color="red")+ # add mean
        # geom_boxplot(width=0.1)+# add median and quartile
        stat_summary(fun.data=mean_sdl, 
                     geom="pointrange", color="red")#Add mean and standard deviation
    
#DV4
p4 <- ggplot(DV4,aes(x=variable,y=value)) +
      geom_violin()+
      # geom_boxplot(width=0.1)+
        # ggtitle(paste("posterior lambda _ age varying_serotype specific",p_year$Site[1]))+
        theme(plot.title = element_text(hjust=0.5,face="bold",size=20,colour = "blue"),
              axis.title.x = element_blank(),
              axis.text.x = element_text(angle = 90,size=6,face = "bold"))+
        coord_cartesian(ylim=c(-0.01,0.3))+
        ylab("DENV4")+
        # stat_summary(fun.y=mean, geom="point", size=2, color="red")+ # add mean
        # geom_boxplot(width=0.1)+# add median and quartile
        stat_summary(fun.data=mean_sdl, 
                     geom="pointrange", color="red")#Add mean and standard deviation
    

library(gridExtra)
library(grid)


lamb <- grid.arrange(p1,p2,p3,p4, ncol=2,nrow=2, top =textGrob(paste("FOI_time varying",step_year,"yr(s)","_serotype specific",site,dataInput),gp=gpar(fontsize=20,col = "blue")))

# save the figure
ggsave(filename=paste("/home/phuong/pCloudDrive/PMA analysis results/FoI/Lambda/FOI timevarying_serotype",step_year,"yr(s)",site,dataInput,".png"), plot = lamb)
}

```

